### ISSUE TITLE
iOS Release build fails after adding RNGE

### ISSUE THREAD

**Issue by rafaelmaeuer** [bberak/nature-of-code-app#10]
with following error: **.../node_modules/rx/dist/rx.all.js: Cannot convert object to primitive value**

**Background**
I am currently working on a little game and lately I tested a release build which failed. I tried to figure out the reason for the error and after stepping back my commits I noticed it was happening just after adding RNGE to my project. I am using newest Version of React Native (0.56.0) and React (16.4.1).

**What exactly is failing?**
Xcode Release Build fails with: `error: File .../testproject.app/main.jsbundle does not exist.`

The Error occurs at one of the last build steps: `Run custom shell script 'Bundle React Native code and Images'` when `.../testproject/node_modules/react-native/scripts/react-native-xcode.sh` is executed to build the main.jsbundle file.

It produces the following Error: `.../testproject/node_modules/rx/dist/rx.all.js: Cannot convert object to primitive value` which seems to happen in `rx.all.js`.

On debug builds no main.jsbundle is created because the metro-packager delivers it while run, so the error doesn't occur.

**Steps to reproduce**
- create testproject `react-native init testproject` 
- open project in xcode and run a release-build: works
- add RNGE to testproject `yarn add react-native-game-engine`
- copy and paste sample code of GameLoop Component Example into App.js (https://www.npmjs.com/package/react-native-game-engine#using-the-gameloop-component)
- clean xcode project and run a release-build: fails

It can also be reproduced by copying only the bundling command and run it in terminal: 
`node .../testproject/node_modules/react-native/local-cli/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output .../testproject.app/main.jsbundle --assets-dest .../testproject.app`

**Note**
I shortened all paths with `.../` due to privacy and better readability.

**Comment by bberak** [comment]
Hi @rafaelmaeuer,

Thanks for the detailed issue! I'll try reproduce your steps and get back to you ASAP.

Cheers!

**Comment by bberak** [comment]
Hi @rafaelmaeuer,

Just to confirm - does the build work fine when you're not using the release configuration?

I was able to reproduce your issue - however my build does work when using debug.

I was also able to confirm that the issues lies with the rx library. If I import the library without React Native Game Engine - I get the same problem. The strange thing is that the rx library is very popular and has not been updated in like 2 years!

This leads me to believe that there has been some recent change/bug introduced into the React Native tooling ecosystem.

If you want to get started quickly - I'd recommend using [Expo](https://expo.io ). It is basically a wrapper for React Native with some goodies. I've found it to be a lot more developer friendly, I wouldn't be surprised if you avoid this issue altogether.

That said, I'll have another think about this problem - perhaps I'll create an issue in the Rx or React Native repos and see if that gets me closer to an answer.

**Comment by rafaelmaeuer** [comment]
Hey @bberak,

yes I can confirm that debug builds are working, as I wrote above: 

> On debug builds no main.jsbundle is created because the metro-packager delivers it while run, so the error doesn't occur.

I guess it is related to some changes with the newest React Native Version, as the RNGE Playground app can be successfully built for release (it uses react native 0.48.1).

Maybe I try Expo, but I'm not a friend of the limitations it has regarding native modules.

The Rx or React Native repos would have been my next steps after checking the issue here. 
So yes lets create an issue there.

**Comment by rafaelmaeuer** [comment]
Hey @bberak,

I was looking into the repos of RN and RX for reporting an issue, then I checked the RX version you are using in RNGE and found it is v4.1.0. As they mention in the readme (https://github.com/Reactive-Extensions/RxJS#note-the-latest-version-of-rxjs-can-be-found-here) there is a newer version in another repo: v6.2.2 (https://github.com/reactivex/rxjs). Maybe using the newest version with RNGE solves the issue?

**Comment by bberak** [comment]
Ahhh, that makes sense why my package wasn't updated in 2 years! 

Thanks @rafaelmaeuer, I'll try integrate the latest package. If it works I'll publish an updated RNGE. I think I should be able to do this over the coming weekend, hopefully sooner though!

**Comment by bberak** [comment]
Hi @rafaelmaeuer,

To speed this up - I'm going to create a branch that uses the latest RxJS (rx-update branch). Unfortunately, there's been lots of changes between v4 and v6 and I'm trying to fix all the issues now. 

Once I've fixed the issues you can use the branch directly.. ```npm install --save git+https://github.com/bberak/react-native-game-engine.git#rx-update```

**Comment by rafaelmaeuer** [comment]
Hi @bberak,

Thanks for your effort and the fast response.
Please let me know when rx-update branch is ready to test.

**Comment by rafaelmaeuer** [comment]
Hi @bberak, any news on this? Didn't see any change in the repo lately...

**Comment by bberak** [comment]
Hi @rafaelmaeuer,

I've been on holidays this week so I didn't find a lot of time to work on this.

I've just pushed some working code to the rx-update branch. You can install it like so:

```npm install --save git+https://github.com/bberak/react-native-game-engine.git#rx-update```

The version is 0.10.1

Since the Rxjs api changed a lot from v4 to v6, I had to rewrite the touch processing code. Please let me know if you experience any issues with this. I've tested the rx-update branch with the handbook and it seemed to work well - but I'm not comfortable with merging this into the master branch just yet..

Cheers!

**Comment by rafaelmaeuer** [comment]
Hey @bberak,

thank your very much and my apology for being pushy on this, while you have been on holidays!!!
I testet the rx-update branch and so far its working, I am able to make release builds.
Give me a note when you merged this into the main branch, I think then the issue can be closed.

Kind regards.

**Comment by bberak** [comment]
Haha all good @rafaelmaeuer - glad it's working. 

Thanks for trying trying out the branch. I'll shoot you a message when I update master - I'll give it some time (just in case). 

Cheers!

**Comment by bberak** [comment]
Hi @rafaelmaeuer,

I've been using the latest branch in a couple of my games and it's been working well.

I've merged this branch into master and published the latest version (```0.10.1```) to **npm**.

Cheers!

**Comment by rafaelmaeuer** [comment]
Hi @bberak,

I tested the current branch and release builds are still working, thanks.

Regards
