### ISSUE TITLE
How to add svg children?

### ISSUE THREAD

**Issue by j-funk** [bberak/nature-of-code-app#13]
Hi there, thanks for this great library, I really like the way it separates the concerns and organizes the code.  

I am trying to use this with `react-native-svg` and have it working to some degree.  However, when I attempt to go beyond a single entity and dynamically add new svg chilren entities to the parent svg I am stuck at a wall.  

Essentially, I am able to make the children available inside the SVG container, however I get the following error when it goes to render:

`...ORTCView_Invalidate]: Unrecognized selector sent to instance )x12345678`

My latest attempt is below...
In `NoteBubble.js`:

```import React, { Component } from 'react';
// imports etc....
class Renderer extends Component {
  render() {
      const { position, width, height } = this.props;
      const x = position[0];
      const y = position[1];
      return (
        <Rect
          x={x}
          y={y}
          width={width}
          height={height}
          fill="yellow"
        />
      );
  }
}

export default (
  position,
  key,
  width = 10,
  height = 10,
) => ({
  position,
  key,
  width,
  height,
  renderer: <Renderer key={key} />,
});
```

In `SvgCanvas.js`:

```
// imports etc ...
class SvgCanvas extends Component {
  render() {
    const { entities } = this.props;
    return (
      <Svg
        width={100}
        height={100}
        viewBox={`0 0 100 100`}
      >
        {entities.map(e => e.renderer)}
      </Svg>
    );
  }
}
export default SvgCanvas;
```

In `systems.js`:

```
import NoteBubble from '../entities/NoteBubble';

function MoveComposition(entities) {
  if (entities.svgCanvas.entities.length) {
    entities.svgCanvas.entities.forEach(bubble => {
      bubble.position[0] += 1;
    });
  }
  return entities;
}

function CreateBubble(entities, { touches }) {
  touches
    .filter(t => t.type === 'press')
    .forEach(t => {
      const bubbleIdx = entities.svgCanvas.entities.length;
      const key = `bubble-${bubbleIdx}`;
      const newBubble = NoteBubble([t.event.pageX, t.event.pageY], key);
      entities.svgCanvas.entities.push(newBubble);
      entities[key] = newBubble;
    });
  return entities;
}

export default [CreateBubble, MoveComposition];
```

in `App.js`

```
export class Designer extends PureComponent {
  render() {
    return (
      <Container>
        <Content>
          <GameEngine running systems={Systems} entities={{
              svgCanvas: {
                 entities: [],
                 renderer: <SvgCanvas />,
              },
          }} />
        </Content>
      </Container>
    );
  }
}
```

**Comment by bberak** [comment]
Hi @j-funk,

Appreciate the kind words.

Whilst I have not used **react-native-svg** a lot - I do remember creating a particle system where I had to add a lot of children: https://github.com/bberak/react-native-game-engine-handbook/blob/master/app/table-of-contents/renderers.js (code is buried somewhere in there) - so I know it's possible.

I don't recall encountering the error you have though.. I'll need to recreate your app to figure this out I feel.. If possible, could you create a repo with a basic setup of your app? If not, I'll create an Expo app and attempt to reproduce the error from there (but this will take me a few days - I'm heading out tonight).

BTW, are you running iOS or Android?

Cheers!

**Comment by j-funk** [comment]
@bberak thank you for your note, indeed you have an example of SVG working in there renderers you linked.  I have that working for now!

**Comment by bberak** [comment]
Awesome @j-funk - I'm glad that helped! 

Let us know when you've released your app (if it's public) - would love to see what the community is working on. Cheers.
