### ISSUE TITLE
Need Typescript types

### ISSUE THREAD

**Issue by xRahul** [bberak/nature-of-code-app#14]
VS Code is throwing the following error when using in a typescript file:

```
Could not find a declaration file for module 'react-native-game-engine'. '/Users/...Project/node_modules/react-native-game-engine/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-game-engine` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-game-engine';`ts(7016)
```

This will require adding a package `@types/react-native-game-engine`

**Comment by bberak** [comment]
Ahhh ok. Thanks @xRahul! I'm not very familiar with Typescript so I'll have to familiarise myself a bit first.

Thanks for raising this issue, I'll tap you on the shoulder when I make progress - will try get to it this week.

**Comment by bberak** [comment]
Apologies for the lateness @xRahul and to other who were waiting for this. Thanks to a PR, I've just published basic Typescript support under version `0.12.0`. Let me know if there are any issues and I'll take a look - please fee free to re-open this issue if that is the case!
