### ISSUE TITLE
How to render composite bodies

### ISSUE THREAD

**Issue by anchetaWern** [bberak/nature-of-code-app#16]
Is there a way to render composite bodies created with MatterJS?
I'm trying to create a maze game. The walls are created using a composite body made up of rectangle bodies. I'm using a composite body so I can add the walls in one go:

```
<GameEngine
  style={styles.container}
  systems={[this.physics, this.moveBall]}
  entities={{
    physics: {
      engine: engine,
      world: world
    },
    playerOneBall: {
      body: ball,
      size: [BALL_SIZE, BALL_SIZE],
      renderer: Circle
    },
    mazeWalls: {
      body: maze,
      color: '#ccc',
      size: [10, 15],
      renderer: Rectangle
    }
  }}
>
</GameEngine>
```

But I couldn't figure out a way to render it properly. It looks like the only way is construct an object consisting of many rectangles to create the walls like so:

```
<GameEngine
  style={styles.container}
  systems={[this.physics, this.moveBall]}
  entities={{
    physics: {
      engine: engine,
      world: world
    },
    playerOneBall: {
      body: ball,
      size: [BALL_SIZE, BALL_SIZE],
      renderer: Circle
    },
    wall1: {
      body: maze,
      color: '#ccc',
      size: [10, 15],
      renderer: Rectangle
    },
   wall2,
   wall3..
  }}
>
</GameEngine>
```

**Comment by bberak** [comment]
Hi @anchetaWern,

Is it possible to loop through the composite bodies of the maze walls entity and render them individually? Pseuocode below:

```
class MazeWallsRenderer {
   render() {
      const bodies = this.props.bodies.children(); //-- Not sure if children() method exists, there must be some equivalent.

      return <View>{bodies.map((x, i) => <Rectangle style={{left: x.position.x, top: x.position.y}} key={i} />)}</View>
   }
}

<GameEngine
  style={styles.container}
  systems={[this.physics, this.moveBall]}
  entities={{
    physics: {
      engine: engine,
      world: world
    },
    playerOneBall: {
      body: ball,
      size: [BALL_SIZE, BALL_SIZE],
      renderer: Circle
    },
    mazeWalls: {
      body: MazeWallsRenderer,
      color: '#ccc',
      size: [10, 15],
      renderer: Rectangle
    }
  }}
>
</GameEngine>

```

There must be a way to loop through the children of a composite body - something like this: http://brm.io/matter-js/docs/classes/Composite.html#method_allBodies

I've done something similar in a particle system a while back, take a look at the Particle and ParticleSystem classes here: https://github.com/bberak/react-native-game-engine-handbook/blob/master/app/table-of-contents/renderers.js - they don't use Matter JS, but the looping concept should be the same.

Let me know how it goes!

**Comment by anchetaWern** [comment]
@bberak thanks! I managed to do it with a similar implementation to yours. Basically, I'm just getting all the walls back from the composite object and assigning them to the `entities` needed by your package:

```
const walls = Matter.Composite.allBodies(maze);
walls.forEach((body, index) => {
  
  const { min, max } = body.bounds;
  const width = max.x - min.x;
  const height = max.y - min.y;
  
  Object.assign(this.entities, {
    ['wall_' + index]: {
      body: body,
      size: [width, height],
      color: 'orange',
      renderer: Rectangle
    }
  });
});
```

The only problem is that the collision detection doesn't seem to work if I move the ball fast enough. It goes through the walls. I found out that it's an issue for a long time now: https://github.com/liabru/matter-js/issues/5

But yeah, it's out of scope of this package so I'm closing it now. Thanks!

**Comment by bberak** [comment]
Awesome! Sounds like a cool project @anchetaWern - let us know when it's done!
