### ISSUE TITLE
How to destroy entities?

### ISSUE THREAD

**Issue by lukechatton** [bberak/nature-of-code-app#17]
What is the proper way to destroy entities? I see there is a method for swapping to a new set of entities, but I'm trying to just remove a single entity.

Also, thanks for the awesome engine! Loving it so far!

**Comment by lukechatton** [comment]
Managed to figure it out by reading through your donkey kong example game. For anyone else stuck on the same problem, checkout https://github.com/bberak/react-native-donkey-kong/blob/master/src/utils/index.js

**Comment by bberak** [comment]
Thanks @lukechatton - all the best with your project. Let me know if you run into any other roadblocks.

Cheers.
