### ISSUE TITLE
redux?

### ISSUE THREAD

**Issue by slothyrulez** [bberak/nature-of-code-app#2]
Do you think is feasible and or interesting integrante with redux?

**Comment by bberak** [comment]
Hmm @slothyrulez, I guess it could be interesting, but I'm not 100% clear on the benefits. I suppose with redux (correct me if I'm wrong), one writes a series of reducers that take the state of the app from point A to point B - and this is not so different to the "systems" in a Component-Entity-System implementation (which is what react-native-game-engine basically is). In that regard, I suppose it would be possible to achieve this with some chopping and changing.

Do you have a particular use-case in mind ? :)

**Comment by slothyrulez** [comment]
Well, I've started toying a bit with your library, mainly moving things around the screen. My frontend dev experience comes from traditional UI development. And I've noted actually what you have mentioned, the systems part feels a lot like reducers, I guess the main advantage will be, have/gain full access to the whole state on the renderers, and take profit of all the prior art done in react + redux. 

On the other side, I'm not pretty sure about the performance if the integration means to pass the time ticks through the store (i'm not saying that has to be done that way).

As an example, i'll see the redux-form https://redux-form.com/7.2.0/ which creates a property on the store  (can have more than one) and manages all I'ts own state there.

**Comment by bberak** [comment]
Sounds interesting @slothyrulez - I'd be keen to hear how that goes :) .. Happy to bounce back ideas, although I'm a redux novice.

Indeed, I was thinking that dispatching a redux "time-tick" action on every frame might be burdensome performance wise - but perhaps not! Let us know in any case!
