### ISSUE TITLE
Move Entities when user tap on screen.

### ISSUE THREAD

**Issue by NALAndroid** [bberak/nature-of-code-app#20]
Hi Admin.
I am using you engine to make a turn-based game.
I want to move character with animation  to a point which user touch on screen.
I read your handbook, but it only has a move when user move you finger on screen (not a tab) or its move using applyForce in Matter. My game donot need to use physics.
Any idea for me ? 
Sory, i'm a beginner of react native.

Thank for helping.

**Comment by bberak** [comment]
Hi @NALAndroid,

I would use an animation system to accomplish this. When you detect a tap - register an animation on the entity you wish to move and perform the movement logic there.

Here is an example of the animation system, you can just copy it: https://github.com/bberak/react-native-donkey-kong/blob/master/src/systems/animation.js

And here is an example on how to use it (pseudocode):

```
character.animations.move = {
   while: () => calculateDistance(character, tap) > 0.1,
   animate: () => {
      character.postition = //-- A little bit closer to the tap.
   }
}
```

Sorry the above example is a bit rushed, I need to head out - let me know if you need more help!

Cheers!

**Comment by bberak** [comment]
Hi @NALAndroid ,

Let me know if you need more help with this issue! Cheers.

**Comment by lexengineer** [comment]
Hello everyone!

@bberak 
I am trying to achieve the same, but looks like `donkey-kong` link doesn't work anymore. Is there any chance that you have an example which may help?

I want to move object with smooth transition to the `user tap` location.

**Comment by bberak** [comment]
Hi @oleksiikiselov,

You can find the source code for the `animation` system (now called `timeline`) in the [template project](https://github.com/bberak/react-native-game-engine-template/blob/master/src/game/systems/timeline.js) - it does pretty much the same thing and more. Here are some examples of how it is used:
- [Updating sprites in response to controls](https://github.com/bberak/react-native-game-engine-template/blob/cbbbeb69b68358f7225267ee1daf02c57fd42362/src/game/components/cuphead.js#L65)
- [Instantiating a camera chake effect](https://github.com/bberak/react-native-game-engine-template/blob/cbbbeb69b68358f7225267ee1daf02c57fd42362/src/game/components/camera.js#L26).

Let me know if you need more info! :)

**Comment by lexengineer** [comment]
@bberak 
I tried to add it to my project, but I am also using Matter.js for creating `sprites/objects` instead of Three.js. I assume I have to add move handler to one of my `sprites/objects` and place timeline logic inside the handler, but still don't know where to initiate this move. Probably inside the move system when touch appears I can call move handler and do a while condition, so it is going to be `true` until my `sprite/object` and `tapped location` positions become equal. 

```
const MoveDolphinSystem = (entities, { touches, time }) => {
  let engine = entities.physics.engine;
  let dolphin = entities.dolphin.body;
  let food = entities.food.body;

  touches
    .filter(t => t.type === 'press')
    .forEach(t => {
      console.log('touch')
    });

  Matter.Engine.update(engine, time.delta);

  return entities;
};
```

This is how my move system looks right now and my goal is to move `dolphin` object when user taps on the screen. As I mentioned I guess I need to call something like `dolphin.move` which will trigger the `timeline`. But maybe I am wrong. Would be good which arguments I can pass to `timeline`.

Any advice is very appreciated, because I am not sure if this is a correct way.

**Comment by bberak** [comment]
Hi @oleksiikiselov,

I'm not really an expert with MatterJS, but I can try give you some pointers.

Most physics engine allow you to apply a force to a body with a vector. I'm pretty sure MatterJS supports this, it would be something like `entities.dolphin.body.applyForce({ x: 0, y: 1 });` - this would make the dolphin jump in the air (the method could also be called `applyImpulse` or something. In this scenario, the physics engine will take care of the animation for you - so you don't need to handle the animation yourself using a timeline or anything.

If that doesn't suit your requirements, you might need to perform several calls to `applyForce` to animate the jump. In this case, you would use the `timeline` system to make the additional calls over several frames of your game - doing this in a `while` loop would not be adequate as the forces would just be accumulated and resolved during the next call to update the physics world. Here are some examples of how you can use the `timeline` system:

```javascript
entities.dolphin.timelines.jump = {
	duration: 400,
	update: (self) => {
		//-- applyForce will get called for each frame
		//-- over the next 400ms
		self.body.applyForce({ x: 0, y: 1 });
	}
}

entities.dolphin.timelines.jump = {
	while: true,
	update: (self) => {
		//-- applyForce will get called each frame, indefinitely
		self.body.applyForce({ x: 0, y: 1 });
	}
}
```

Hope that helps!
