### ISSUE TITLE
Move this awesome repo to react-native-community

### ISSUE THREAD

**Issue by MoKhajavi75** [bberak/nature-of-code-app#22]
Hey!

This is a great repo and I think if you move it to [react-native-community](https://github.com/react-native-community), it will receive more and more focus and improvements!

**Comment by bberak** [comment]
Thanks for the kind words @MohamadKh75 

I'll give it some thought.. Not even sure how I would go about doing this - I'll need to give the RN Community rules a bit of a read..

Cheers for the heads up!

**Comment by MoKhajavi75** [comment]
I asked about the conditions to do it...
I'll be back to you whenever I understand :grin:

**Comment by MoKhajavi75** [comment]
Well, you can ask [here](https://github.com/react-native-community/discussions-and-proposals/issues)!

**Comment by bberak** [comment]
Thanks @MohamadKh75 - I'll have a read and give it some thought.. Cheers!
