### ISSUE TITLE
Matter js strange behaviour of non-static objects.

### ISSUE THREAD

**Issue by artemukolov** [bberak/nature-of-code-app#35]
Hello I added matter-js engine to my react-native-game-engine project. And then I noticed pretty weird behaviour of non-static objects. They jump and can't catch static position. Circle objects have same behaviour.

![](https://s3.gifyu.com/images/ezgif-4-df443f481dc1.gif)

I started my project via this post

https://medium.com/better-programming/flappy-bird-with-react-native-game-engine-and-matter-js-d5673f50eb9

Did somebody face with this issue? Thanks.

**Comment by bberak** [comment]
Hi @artemukolov,

Whilst I'm not an expert in MatterJS - that looks like a config issue. Perhaps you've set elasticity or restitution or something which is causing the bounciness? 

I've worked on something similar, you can check it out here: https://github.com/bberak/react-native-game-engine-handbook/blob/master/app/physics/rigid-bodies/index.js

Let me know if that helps.

**Comment by artemukolov** [comment]
Yeah, I tried to copy your code. But it has same issue. This is full text of application. I just added couple of boxes.




`import React, { Component } from "react";
import { StatusBar, Dimensions, View } from "react-native";
import { GameEngine } from "react-native-game-engine";
import Matter from "matter-js";

class Box extends Component {
    constructor(props) {
        super(props);
    }

    render() {
        const width = this.props.size[0];
        const height = this.props.size[1];
        const x = this.props.body.position.x - width / 2;
        const y = this.props.body.position.y - height / 2;
        const angle = this.props.body.angle;

        return (
            <View
                style={
                    {
                        position: "absolute",
                        left: x,
                        top: y,
                        width: width,
                        height: height,
                        transform: [{ rotate: angle + "rad" }],
                        backgroundColor: this.props.color || "pink"
                    }
                }
            />
        );
    }
}

let boxIds = 0;

const distance = ([x1, y1], [x2, y2]) =>
    Math.sqrt(Math.abs(Math.pow(x2 - x1, 2) + Math.pow(y2 - y1, 2)));

const Physics = (state, { touches, time }) => {
    let engine = state["physics"].engine;

    Matter.Engine.update(engine, time.delta);

    return state;
};

const CreateBox = (state, { touches, screen }) => {
    let world = state["physics"].world;
    let boxSize = Math.trunc(Math.max(screen.width, screen.height) * 0.075);

    touches.filter(t => t.type === "press").forEach(t => {
        let body = Matter.Bodies.rectangle(
            t.event.pageX,
            t.event.pageY,
            boxSize,
            boxSize,
            { frictionAir: 0.021 }
        );
        Matter.World.add(world, [body]);

        state[++boxIds] = {
            body: body,
            size: [boxSize, boxSize],
            color: boxIds % 2 == 0 ? "pink" : "#B8E986",
            renderer: Box
        };
    });

    return state;
};

const MoveBox = (state, { touches }) => {
    let constraint = state["physics"].constraint;

    //-- Handle start touch
    let start = touches.find(x => x.type === "start");

    if (start) {
        let startPos = [start.event.pageX, start.event.pageY];

        let boxId = Object.keys(state).find(key => {
            let body = state[key].body;

            return (
                body &&
                distance([body.position.x, body.position.y], startPos) < 25
            );
        });

        if (boxId) {
            constraint.pointA = { x: startPos[0], y: startPos[1] };
            constraint.bodyB = state[boxId].body;
            constraint.pointB = { x: 0, y: 0 };
            constraint.angleB = state[boxId].body.angle;
        }
    }

    //-- Handle move touch
    let move = touches.find(x => x.type === "move");

    if (move) {
        constraint.pointA = { x: move.event.pageX, y: move.event.pageY };
    }

    //-- Handle end touch
    let end = touches.find(x => x.type === "end");

    if (end) {
        constraint.pointA = null;
        constraint.bodyB = null;
        constraint.pointB = null;
    }

    return state;
};

const CleanBoxes = (state, { touches, screen }) => {
    let world = state["physics"].world;

    Object.keys(state)
        .filter(key => state[key].body && state[key].body.position.y > screen.height * 2)
        .forEach(key => {
            Matter.Composite.remove(world, state[key].body);
            delete state[key];
        });

    return state;
};

Matter.Common.isElement = () => false; //-- Overriding this function because the original references HTMLElement

export default class App extends Component {
    constructor() {
        super();
    }

    render() {
        const { width, height } = Dimensions.get("window");
        const boxSize = Math.trunc(Math.max(width, height) * 0.075);

        const engine = Matter.Engine.create({ enableSleeping: false });
        const world = engine.world;
        const body = Matter.Bodies.rectangle(width / 2, -1000, boxSize, boxSize, { frictionAir: 0.021 });
        const body2 = Matter.Bodies.rectangle(width / 2, -1200, boxSize, boxSize, { frictionAir: 0.021 });
        const body3 = Matter.Bodies.rectangle(width / 2, -1400, boxSize, boxSize, { frictionAir: 0.021 });
        const floor = Matter.Bodies.rectangle(width / 2, height - boxSize / 2, width, boxSize, { isStatic: true });
        const constraint = Matter.Constraint.create({
            label: "Drag Constraint",
            pointA: { x: 0, y: 0 },
            pointB: { x: 0, y: 0 },
            length: 0.01,
            stiffness: 0.1,
            angularStiffness: 1
        });

        Matter.World.add(world, [body, body2, body3, floor]);
        Matter.World.addConstraint(world, constraint);

        return (
            <GameEngine
                systems={[Physics, CreateBox, MoveBox, CleanBoxes]}
                entities={{
                    physics: { engine: engine, world: world, constraint: constraint },
                    box: { body: body, size: [boxSize, boxSize], color: "pink", renderer: Box },
                    box2: { body: body2, size: [boxSize, boxSize], color: "pink", renderer: Box },
                    box3: { body: body3, size: [boxSize, boxSize], color: "pink", renderer: Box },
                    floor: { body: floor, size: [width, boxSize], color: "#86E9BE", renderer: Box }
                }}
            >

                <StatusBar hidden={true} />

            </GameEngine>
        );
    }
}`

And there is result 

![](https://s3.gifyu.com/images/ezgif-4-66c9082c4da8.gif)

**Comment by bberak** [comment]
Hi @artemukolov,

What happens if you just add one box to the ground? Is it still bouncing? Also, are you using the same version of MatterJS I used  in https://github.com/bberak/react-native-game-engine-handbook ?

**Comment by artemukolov** [comment]
@bberak 
1) One box doesn't bounce.
2) I tried do it on current 0.14.2 and on 0.13.0. Behaviour is same

**Comment by bberak** [comment]
Hi @artemukolov,

Can you give me access to the repo or preferably a [snack](https://snack.expo.io) so that I can play around with this?

I also think asking this question in the MatterJS project will give you better opinions then my own (I've only used MatterJS a few times) - but I will try my best to help :)

**Comment by artemukolov** [comment]
@bberak Hello, sorry for long silence. 
https://snack.expo.io/@artemukolov/rn-matter-js-issue

Please, take a look. Try to add boxes. I tested it on my device via QR code.

**Comment by bberak** [comment]
Hi @artemukolov,

I've tried you Snack on my physical device and an iOS simulator - and it looks like it's working just fine. I assume you've fixed the issue :) Please let me know otherwise!
