### ISSUE TITLE
Best way to detect touch target

### ISSUE THREAD

**Issue by artemukolov** [bberak/nature-of-code-app#36]
Hello. I tried to use your method to detect touch target: 

let boxId = Object.keys(state).find(key => {
let body = state[key].body;
return (
        body &&
        distance([body.position.x, body.position.y], startPos) < 25
    );
});

It works, but I think this is not better way to find object during each iteration. In same time your documentation has wrong approach

  touches.filter(t => t.type === "move").forEach(t => {
    let finger = entities[t.id];

This is don't work.

I noticed that every touch object has touch.event.target field. This is a number. An it's unique for each of object. But I can't combine this index and object from entities. Could you please help me?

Thanks a lot.

**Comment by majonathany** [comment]
Hmm, in finger = entities[t.id], what is t.id? In order to get the position of the swipe, I do something like this:

let move = touches.find(x => x.type === 'move');

        if (move) {

            let newX = this.state.currentItem.position.x + move.delta.pageX;
            let newY = this.state.currentItem.position.y + move.delta.pageY;
        }

**Comment by bberak** [comment]
Hi @artemukolov,

Each `touch` in the `touches` array has an `id` property that corresponds to the finger that was used to create the touch event. So if you have multiple fingers on the screen, the ids would be 1,2,3 etc.. From memory, the example you are referring to used numbers for the entity keys. Therefore `entities[t.id]` would refer to one of the game objects, which I would move according to the touch. That way, the game object follows the finger.

I think a simple but effective way to detect the touch target would be to iterate over your game objects and find the one closest to the touch (maybe ignore objects more than 25 points away). Unless you have lots of game objects - this should be fairly quick.

Let me know if that helps!

**Comment by bberak** [comment]
Hi @artemukolov - please re-open if you need to discuss further.
