### ISSUE TITLE
touches long-press does not work properly

### ISSUE THREAD

**Issue by anhba817** [bberak/nature-of-code-app#37]
Hi,
I'm a newbie of RNGE.
I've read your tutorial about using GameEngine: https://github.com/bberak/react-native-game-engine#using-the-gameengine-component and I want to try all touches event: press, start, end, move and long-press.
Just write to console if the event happen:
touches.filter(t => t.type === "long-press").forEach(t => {
        console.log("Long press");
    });
It works OK for press, start, end and move but for long-press it seem doesn't work properly. I tested many times but it can only detect some (and totally random, I don't know how to make the event happen).
Do you have any idea why this happen ?
I'm using react-native 0.61 and react-native-cli 2.0.1
Thank you

**Comment by bberak** [comment]
Hi @anhba817,

Do you have any styles on the GameEngine component or it's parent? Perhaps that is causing some interference.

Also, are you using Android or iOS? A real device or simulator?

If you get a chance to put your code into a [snack](https://snack.expo.io) I could take a closer look.

Cheers!

**Comment by anhba817** [comment]
Hi @bberak ,
Thank you for replying.
I just use your example code and replace move event by long-press.
I tested it on expo simulator and it works fine:
https://snack.expo.io/@anhba817/71993d

But when I run on my Android phone, the problem happens.
I'm using a Xiami Mi8 Lite with Android 9
Regards,

**Comment by bberak** [comment]
Thanks for the snack @anhba817, that really helps.

I tried your example on an iOS device, iOS simulator and Android simulator - and it worked in all three environments. Unfortunately, I don't have an a Android device anymore.

Can you try updating the styles with the following:

```javascript

//-- Try this first
const styles = StyleSheet.create({
  container: undefined
});

//-- Then try this
const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject
  }
});
```
I'm not sure if that would help, but I'm just curious. I find it strange that the start, end, press and move events are firing, but not long-press..

**Comment by anhba817** [comment]
I tried again with the styles as your suggestion, but it didn't help.
I used another Android device and the problem happen also, so I assume that it happen for all real Android devices.
I'm wondering why the long-press is different with others, do you have any idea ?
Thanks

**Comment by bberak** [comment]
Sorry @anhba817, I'll need to get my hands on a real device to troubleshoot this. I'll see if there's a cheap phone for sale somewhere or if I can borrow one of a friend..

**Comment by bberak** [comment]
In the mean time @anhba817, if you're receiving the 'start' and 'end' touch events - you should be able to detect your own 'long-press' events by calculating the time interval between 'start' and 'end' and comparing it to 500ms or 1000ms as an example.

**Comment by anhba817** [comment]
Hi @bberak,
I think I figured out the root cause. I see that you detect the long press event by checking if start event happen and after 700ms there is no move or end events happen. So I assumed that my Android phones are too sensitive so that when you press and hold, just one small vibration of your finger make the move event happen.
I tested my assumption by add more code to detect move events and yes, a lot of move events received when I pressed and hold.
I'm thinking about how to solve this, do you have  any idea?
Regards

**Comment by bberak** [comment]
Hi @anhba817,

Thanks for debugging the issue - nice find! The [Default Touch Processor](https://github.com/bberak/react-native-game-engine/blob/master/src/DefaultTouchProcessor.js) currently accepts time thresholds for triggering presses and long-presses. Perhaps we can add in a third parameter (sensitivity - or something) that will ignore minor, consecutive finger movements. This should cause the long-press to fire, and also prevent redundant touches from flooding your systems.

What do you think?

**Comment by anhba817** [comment]
That's a good idea! But I'm really new to JavaScript so I need more time to really understand how the code works and implement what I want. Could you please share some code snippet for your idea?
Best Regards,

**Comment by bberak** [comment]
Hi @anhba817,

The change will need to be made in the RxJS-heavy code of the DefaultTouchProcessor component - this is quite convoluted actually. I'll have a think about how to implement this, share the code with you, and perhaps you can try it out on your device. If the test is successful, we'll probably move the change into the master branch.

**Comment by anhba817** [comment]
Hi @bberak,
Sure, I can help you to test this. I also have tried to code but not successful yet :(
Thanks

**Comment by anhba817** [comment]
Hi @bberak ,
After a few week learning js and rxjs, I now can fix the issue. I created a pull request, please help to review. The code has been tested on my Android phones, Android simulator and iOS simulator and all work fine. I cannot test it on iOS device because I do not have one.
Thanks

**Comment by bberak** [comment]
Hi @anhba817,

You are awesome - thank you! 

Yes, I'll test it out on my device and merge your PR into master if it works :)

I might have to do it this weekend though - I've been trying to get away from the computer a bit during the silly season..

**Comment by bberak** [comment]
Hi @anhba817,

I've just processed a couple pf PRs and releases. 

Yours will be next (in a few days time)!

Sorry for the delay.
