### ISSUE TITLE
Simple tutorial for making a game using react-native-game-kit

### ISSUE THREAD

**Issue by RyszardRzepa** [bberak/nature-of-code-app#4]
Hey,

I am playing with ur lirary and works great!
Are u planing on making a tutorial how to make a mobile game with ur library or u could refer a link to get a good start?

**Comment by bberak** [comment]
Hi @RyszardRzepa,

Thanks for the feedback! I'm currently working on a simple platforming game/clone: https://github.com/bberak/react-native-donkey-kong 

I'm planning on writing up a couple of blogs posts that chronicle the development - but that probably won't be ready for a few weeks..

That said, all the source code is on github. To get started you can try the following commands:

```
git clone https://github.com/bberak/react-native-donkey-kong.git
cd react-native-donkey-kong/rn
npm install
npm run dev
```

Let me know how it goes and if it was useful or not :)

Oh, you can also have a look at the handbook - it contains various example (but no tutorials unfortunately): https://github.com/bberak/react-native-game-engine-handbook

Cheers!
