### ISSUE TITLE
Addition touch events to GameEngine

### ISSUE THREAD

**Issue by adimallikarjunareddy** [bberak/nature-of-code-app#41]
Is there a way to pass additional touch events to `GameEngine`? Or in other words can we configure `GameEngine` to receive inputs other than the default touch events?

If we are using game controllers with the device, we may need to handle these events instead of relying on touch events.

Currently `systems` components are invoked if there is any touch event and I would like to know if there is any way to send additional events along with it?

**Comment by bberak** [comment]
Hi @adimallikarjunareddy,

The `GameEngine` accepts a `touchProcessor` prop that you can use to provide your own touch processing logic. You can take a look at the [DefaultTouchProcessor](https://github.com/bberak/react-native-game-engine/blob/master/src/DefaultTouchProcessor.js) to see how the interface/api works.

Alternatively, you can write a custom system that will read input from your game controller and inject it into the `args` that get passed down to subsequent systems. I use this paradigm quite often.. Here is an example of my [GamepadController system](https://github.com/bberak/react-native-game-engine-template/blob/master/src/game/systems/gamepad-controller.js), here is how I add it to the [systems array](https://github.com/bberak/react-native-game-engine-template/blob/master/src/game/systems/index.js) and here is how I would use it:

```javascript
const SomeOtherSystem = (entities, { touches, gamepadController }) => {
   if (gamepadController.a)
      console.log("Button 'a' was pressed");
 
   return entities;
};
```

Let me know if that helps @adimallikarjunareddy :)
