### ISSUE TITLE
After reseting a level, getting random collisions in game

### ISSUE THREAD

**Issue by ryanvanbelkum** [bberak/nature-of-code-app#45]
👋I'm not sure if this is an issue with Matter JS, or with RNGE, but I've got an issue that is plaguing me.

I've got a game, where a spacecraft dodges objects in space. Upon a collision, I reset the game. Note: I'm using Matter for physics. 

I do the following upon reset...
```
Matter.World.clear(engine.world);
Matter.Engine.clear(engine);

// recreate world and swap game engine with new entities
this.refs.engine.swap(newEntities);
```

BUT when playing the reset game, my collision handler will register collisions with objects that aren't appearing on the screen. Almost like there is an object there and the image isn't being rendered. Just reaching out to see if I'm missing something basic. Thank you!

**Comment by bberak** [comment]
Hey @ryanvanbelkum,

Sorry for the late response. Restarts can be tricky, especially if you are maintaining some state (like the physics engine and world) from level to level.

Can you verify that your entities are being swapped with your new entities? A simple `console.log` from one of your systems should answer that..

I haven't used `MatterJS` a lot, but the last time I used it I ended up generating a new engine and new world with each reset.. I didn't find any noticeable decrease in performance - and I think removing the need to maintain state between level changes and resets is quite clean.  I wonder if I stumbled upon the same bug as you but didn't document it.. Essentially, I created a LevelX function that would generate a new set of entities when called - and one of the entities would contain the fresh physics engine and world:

LevelOne.js:

```javascript
export default () => {

    let engine = Matter.Engine.create({ enableSleeping: false });
    let world = engine.world;

    world.gravity = { x: 0, y: 2 };

    return {
        physics: { engine: engine, world: world },

        platform1: Platform(
            world,
            { x: cx, y: offsetY + 35 },
            0,
            platformWidth * 0.25
        ),
        platform2: Platform(
            world,
            { x: cx - 15, y: offsetY + 100 },
            0,
            platformWidth * 0.8
        ),
        platform3: Platform(
            world,
            { x: cx + 15, y: offsetY + 165 },
            -0.07,
            platformWidth * 0.8
        ),

        camera: { offsetY: 0 }

        ...etc
    };
};
```

I would also call the function above when swapping entities during rests (after a game-over event or things like that). 

Let me know how you go :)
