### ISSUE TITLE
TypeError with system args

### ISSUE THREAD

**Issue by StolenPkM** [bberak/nature-of-code-app#47]
Hi, i'm new and tried to use react-native-game-engine but  i got an error when i create a new systems for <GameEngine />.  After some research still dont understand why. 
<img width="400" alt="Capture d’écran 2020-02-06 à 12 23 08" src="https://user-images.githubusercontent.com/25509899/73932876-8551f500-48db-11ea-8ef1-7c04292818c8.png">

i'm at the beginning so this is my code.

<img width="944" alt="Capture d’écran 2020-02-06 à 12 25 08" src="https://user-images.githubusercontent.com/25509899/73933044-eaa5e600-48db-11ea-9a95-ea21b3ddc43c.png">

and my systems code 

<img width="543" alt="Capture d’écran 2020-02-06 à 12 25 47" src="https://user-images.githubusercontent.com/25509899/73933067-fbeef280-48db-11ea-8a16-c3025d8d3a84.png">

**Comment by bberak** [comment]
Hi @StolenPkM,

That's very odd, your code looks fine to me..

Can you replace the line where you set your `systems` prop with this (just for debugging):

```
systems={[(entities) => { console.log("tick"); return entities; }]} 
```

The RNGE library also contains a component called `GameLoop` (not recommended for use), are you importing that anywhere? (Doesn't look like it - but can't hurt to ask)..

Anyhow, let me know if the change above shows up in the console and we'll go from there :)

**Comment by StolenPkM** [comment]
Hi @bberak  ! thanks for your quick answer ! 
your sentence :
systems={[(entities) => { console.log("tick"); return entities; }]}  works!
that's odd because now i retry like as wrote before and now it's work too.

Thanks a lot !

**Comment by bberak** [comment]
Awesome @StolenPkM!
