### ISSUE TITLE
Game Engine with sprite sheet package

### ISSUE THREAD

**Issue by StolenPkM** [bberak/nature-of-code-app#48]
Hi,

I would like to know if it's possible to add sprites sheets to game engine. I see rn-sprite-sheet package but i dont understand how combinate them. If someone did it or  have any idea to how make it or any substitute, i'll take it!!

Thanks a lot,

Sincerely Yours!

**Comment by bberak** [comment]
Hi @StolenPkM,

I'm not sure if this is exactly what you were after, but I've added a `Sprite` component to the template project, you can see the source here: https://github.com/bberak/react-native-game-engine-template/blob/master/src/game/components/sprite.js

And here is an example of how you can use it: https://github.com/bberak/react-native-game-engine-template/blob/master/src/game/components/cuphead.js

Let me know if you need more info, cheers!
