### ISSUE TITLE
Roll Ball Game using this library

### ISSUE THREAD

**Issue by keisan1231** [bberak/nature-of-code-app#52]
By using this library, can I make roll ball game via acceleration sensor？🤔

**Comment by bberak** [comment]
Why not, hat's a good idea :) I tried to do something similar using a shake mechanic... It didn't turn out very well though hah!

Let me know how it goes, would love to see what you come up with!

**Comment by bberak** [comment]
PS - I recently discovered [this neat little game](https://apps.apple.com/us/app/shaky-shuttle/id1495102831) that uses a tilt mechanic. The developer wrote up a [great article here](https://dev.to/ryanvanbelkum/building-a-mobile-game-using-react-native-3320).

**Comment by keisan1231** [comment]
Thanks a lot!!!

I also discovered [this](https://heartbeat.fritz.ai/creating-an-accelerometer-powered-maze-game-in-react-native-9daedb5740b3)😲

**Comment by bberak** [comment]
Nice, great concept! Thanks for linking.
