### ISSUE TITLE
Is it possible to use phaser with react-native-game-engine?

### ISSUE THREAD

**Issue by medmo7** [bberak/nature-of-code-app#58]
Hello, 
Thanks for this making this package. I'm looking to integrate a game into a react-native app, and i'm little lost as i cant find resources on how to handle things like tile-maps and level generation. I ask if a can use phaser with this lib because there  is a lot of resources around it.

It would be great if game dev tutorials are made using react-native-game-engine.
 
Thank you.

**Comment by bberak** [comment]
Hi @medmo7,

I apologise for the lack of documentation and tutorials - I've been meaning to write up some blog, but just haven't had the time :(

react-native-game-engine is quite lightweight in that it doesn't come with tools for tile map, level, sound and art generation. It is however highly extensible and tool-friendly (in my opinion anyway) dues to its [component-entity-system](https://github.com/bberak/react-native-game-engine#managing-complexity-with-component-entity-systems) architecture.

There are some sibling projects that might help you evaluate the library and provide some examples on how to get started:

- https://github.com/bberak/react-native-game-engine-handbook
- https://github.com/bberak/react-native-game-engine-template

These articles might also help:

- https://medium.com/@williamyang93/my-journey-with-react-native-game-engine-part-i-starting-the-project-bbebcd2ccf6
- https://geekyants.com/blog/react-native-game-development---a-salient-guide-75
- https://dev.to/ryanvanbelkum/building-a-mobile-game-using-react-native-3320
- https://pusher.com/tutorials/react-native-pong-game
- https://www.youtube.com/watch?v=qBGnfULn8W4
- https://medium.com/hackernoon/making-a-platforming-game-with-react-native-4682b4d4d209

Hope that helps!

**Comment by medmo7** [comment]
Thanks a lot for your valuable answer, i will try to use these blog posts to build my endless runner game.  Thanks for the effort.

**Comment by bberak** [comment]
Don't mention it @medmo7 - I need to write up some more content :) 

Let us know how your game comes along!

**Comment by medmo7** [comment]
Sorry to come back on this, i would appreciate if you can give some tips on how to use tileMaps with `react-native-game-engine`, especially those generated by softwares like Tiled.
