### ISSUE TITLE
How can i catch in Entity onPress event and value  on System.js 

### ISSUE THREAD

**Issue by mahiraltinkaya** [bberak/nature-of-code-app#62]
Hello, How can I capture the onPress event in an entity in the System? I tried something but gived below error.

![image](https://user-images.githubusercontent.com/25014707/116085161-35f61100-a6a7-11eb-9250-7c1d30d9f1e8.png)

![image](https://user-images.githubusercontent.com/25014707/116084886-e9123a80-a6a6-11eb-840e-d5a132f0d281.png)

**Comment by bberak** [comment]
Hi @mahiraltinkaya,

Something like that should work. I think you need to do a check for null though:

```javascript
function GameContainer(props) {
  const game = useRef(null);
  
  return (
      <GameEngine
        type="text"
        ref={game}
        entities={{
          cubes: {
            result: (e) => {
              game.current && game.current.dispatch({ type: "respone", data: e })
            },
            renderer: <Cubes />
          }
        }}
      />
  );
}
```

Let me know if that helps!

**Comment by mahiraltinkaya** [comment]
Hi @bberak ;
This works really well. Thank you for the answer. It has been very useful for me. Greetings.

**Comment by bberak** [comment]
No problems @mahiraltinkaya glad it helped! :)
