### ISSUE TITLE
Add animation for moving

### ISSUE THREAD

**Issue by hoanghai9650** [bberak/nature-of-code-app#70]
Hi, 
First of all, thanks you so much for this awesome library.
I'm creating Snake game with this library but the head of snake move so lagging.
I have tried RN animated but it's seem fail.
Do you have any idea for me to add some transition moving animation?
Thanks so much.

**Comment by bberak** [comment]
Hi @hoanghai9650,

Can you explain a bit more about what you mean you say "the head of snake move so lagging"?

What FPS is your JS and UI thread running at? If 60, then the transition should appear pretty smooth.. Does your snake move forward a set number of pixels at a time? If so, can you reduce this amount to make it smoother?

☺️

**Comment by hoanghai9650** [comment]
Hi @bberak ,
Yes I set number of pixels everytime the head is moving, so it's make the head move laggy, it's not smooth like animation transition. I've already tried to add animated but it's failed. Can you help me with that?
Thank you.

**Comment by bberak** [comment]
What frame rate are you getting for your [JS and UI threads](https://reactnative.dev/docs/performance#what-you-need-to-know-about-frames)?

If you are getting around 30-60fps - then reducing the movement to 1 px/pt each frame should give you a smooth result? 

On the other hand, if you are getting 10fps - then any movement adjustments will still probably not yield a smooth result 🤔..

**Comment by hoanghai9650** [comment]
Hi @bberak,
I've already solved it.
But is there any way for me to set infinity background image ?

**Comment by bberak** [comment]
Hi @hoanghai9650,

Could you explain a bit more what you mean by infinity background image within the context of a snake game?

**Comment by hoanghai9650** [comment]
Hi @bberak,
No, I just ask for another project

**Comment by bberak** [comment]
Okay, could you still explain what you mean by infinity background? Do you mean a background image that repeats? If so try use the ImageBackground component with a resizeMode of `repeat`: https://reactnative.dev/docs/image#resizemode

**Comment by hoanghai9650** [comment]
Thanks for fast reply,
But how can I move background image like this video :[youtube.com/watch?v=p2l04VawHe8](https://www.youtube.com/watch?v=p2l04VawHe8)
I'm using react-native-game-engine with matterjs

**Comment by bberak** [comment]
Here's a snippet from a very old project of mine:

```
import React, { Component, } from 'react'
import { View, Text, Image } from 'react-native'
import EStyleSheet from 'react-native-extended-stylesheet';
import * as Animatable from "react-native-animatable";

class Background extends Component {
  
  constructor(props) {
    super(props)
    this.state = {}
  }

  render() {
    return (
      <View style={[css.container, this.props.containerStyle]}>
        <Animatable.Image 
          useNativeDriver={true}
          animation={"slideInDown"}
          duration={16000}
          iterationCount={"infinite"}
          easing={"linear"}
          style={css.backgroundImage} 
          resizeMode={this.props.resizeMode || "repeat"}
          source={this.props.imageSource || require('../images/noise.png')}
          blurRadius={this.props.blurRadius}>
        </Animatable.Image>
        <View style={css.contentContainer}>
            {this.props.children}
        </View>
      </View>
    )
  }
}
```

The way it worked was to take a very long repeating image, and make it animatable using the `react-native-animatable` library. I then applied a slow and infinitely repeating animation to the image. I'm sure there's better ways to achieve this now - but I hope that helps 🙏

**Comment by hoanghai9650** [comment]
Wow thanks so much for that support, I will try now
