### ISSUE TITLE
Support for Expo SDK 43, 44, 45

### ISSUE THREAD

**Issue by freewill777** [bberak/nature-of-code-app#72]
Would very much appreciate if you could make this available via Expo SDK 43 or 44 or 45.

**Comment by bberak** [comment]
Hey @freewill777 👋,

This library should work out of the box on any Expo SDK.. What issues are you seeing? Or are you referring to https://github.com/bberak/react-native-game-engine-template ?

**Comment by matthops** [comment]
I've upgraded a fork of this locally and it seems to be working as expected. I'll make sure I didn't miss any breaking changes between 42-46 and try to get a PR together soon.

**Comment by bberak** [comment]
That's awesome of you @matthops - thanks so much 🙇‍♂️🙇‍♂️

**Comment by matthops** [comment]
Just submitted a PR - let me know if I'm missing anything!

**Comment by bberak** [comment]
Hey @freewill777,

I've just merged @matthops PR that added support to the handbook project for Expo SDK 46. Thanks again @matthops 🔥

**Comment by 3rdp** [comment]
I assume Expo app wasn’t rebuilt and redeployed, because it still uses Expo SDK 42, which is outdated now.

**Comment by bberak** [comment]
Hey @3rdp,

Are you referring to the app hosted by Expo or something? If so, yes, that hasn't been updated for a very long time. 

You should be able to clone the repo and run it from your Expo GO app locally.
