### ISSUE TITLE
GameEngine re-rendering on entities change

### ISSUE THREAD

**Issue by madebylo** [bberak/nature-of-code-app#79]
I have the following problem:

When someone joins my game, my onlineUserEntities change correctly and the GameEngineComponent function is executed again. That works without any issues. I verified this with a "console.log".

However, nothing changes on my display. The GameEngine apparently doesn't notice the change in the entities and doesn't show the new user on the screen. They are there, as I can tell from the collisions in my game, but they are not displayed.

If I give my GameEngine a key that always changes, the entire GameEngine is reloaded. That works, and then the opponent is also displayed. However, the map is also reloaded and all other entities, which is really not optimal for the game flow.

I hope someone can help me.

Here's my code:

`// GameEngineComponent.js
import { GameEngine } from "react-native-game-engine";
import PhysicsSystem from "./PhysicsSystem";
import cameraSystem from "./cameraSystem";
import leagueoflegends from "../maps/leagueoflegends/leagueoflegends";
import createUserEntity from "../userEntityFactory";
import handleOnlineUser from "../online/handleOnlineUser";
import { engine, world } from "./PhysicsSetup";
import { Dimensions } from "react-native";

import React, {
  useState,
  useEffect,
  useRef,
  useImperativeHandle,
  forwardRef,
} from "react";

import { myUserEnityMove, myUserEnityStop } from "../userEntityControls";

function getRandomInt(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

const userId = getRandomInt(0, 1000);

function GameEngineComponent({ scale, keepCentered }, ref) {
  //#region UseState & UseRef & Variablen

  //useState
  const [useCamerSystem, setUseCamerSystem] = useState(true);
  const [currentMap, setCurrentMap] = useState(leagueoflegends);
  const [onlineUserEntities, setOnlineUserEntities] = useState({});
  const [myUserEntity, setMyUserEntity] = useState(
    createUserEntity(userId, "tank", 100, 100)
  );

  //useRef
  const scaleRef = useRef(scale);
  scaleRef.current = scale;

  const keepCenteredRef = useRef(keepCentered);
  keepCenteredRef.current = keepCentered;

  const useCamerSystemRef = useRef(useCamerSystem);
  useCamerSystemRef.current = useCamerSystem;

  //variablen
  const myTranslateX = -(
    Dimensions.get("window").width -
    Dimensions.get("window").width * scale
  );

  //#endregion

  //#region Joystick Moverment

  useImperativeHandle(ref, () => ({
    //Wenn der User den Joystick bewegt:
    handleJoystickMove: (dx, dy) => {
      if (myUserEntity && myUserEntity.body) {
        myUserEnityMove(myUserEntity.body, dx, dy);
      }
    },
    //Wenn der User den Joystick loslässt
    handleJoystickRelease: () => {
      if (myUserEntity && myUserEntity.body) {
        myUserEnityStop(myUserEntity.body);
      }
    },
  }));

  //#endregion

  //#region Set Entities

  //Standard Entities Setzen!
  const initialEntities = {
      physics: { engine: engine, world: world },
      userEntity: myUserEntity,
      map: currentMap,
      scale: scaleRef,
      keepCentered: keepCenteredRef,
      useCameraSystem: useCamerSystemRef,
    }

  //Online User Abrufen!
  useEffect(() => {
    handleOnlineUser(userId, 1, myUserEntity, world, setOnlineUserEntities);
  }, []);

  const allEntities = {
      ...initialEntities,
      ...onlineUserEntities,
  }

  //#endregion

  //#region View

  return (
    <GameEngine
      systems={[PhysicsSystem, cameraSystem]}
      entities={allEntities}
      style={{
        transform: [{ scale: scale }, { translateX: myTranslateX }],
      }}
    />
  );

  //#endregion
}

export default forwardRef(GameEngineComponent);
`

**Comment by bberak** [comment]
Hi @madebylo,

Can you try and use the `swap` method on the GameEngine to insert your new entities? (You'll need a ref on the GameEngine to do that)..

I imagine this will reset the entire state of your game though.. I

Perhaps the easiest method would be to dispatch an event to the GameEngine that a new user has come online - and then insert the user into the entities using a system. Again, you'll need a ref to the GameEngine..

```
function handleOnline(...) {
   this.gameEngine.dispatch({ type: "spawn-user", userId, userEntity);
}

// Register a new system
function spawnSystem(entities, { events }) {
   const spawnEvents = events.filter(x => x.type === 'spawn-user');
   
    if (spawnEvents.length) {
         // Handle logic for adding new users to entities
    }

   return entities
}
```

Let me know how it goes..

**Comment by madebylo** [comment]
Hey @bberak, 

Thank you for your quick response, I have already solved the problem with swap.
"Problem" might be the wrong word, reading the documentation thoroughly would have been enough :D

Sorry and thank you :)

**Comment by bberak** [comment]
No problems at all @madebylo  -- glad you sorted it out :)
